# Generated by Django 5.1.3 on 2025-01-09 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengadaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pengadaan', models.DateField()),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status_pengadaan', models.CharField(choices=[('pending', 'Pending'), ('selesai', 'Selesai'), ('dikirim', 'Dikirim')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_supplier', models.CharField(max_length=255)),
                ('alamat', models.TextField()),
                ('kontak', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pengiriman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pengiriman', models.DateField()),
                ('status_pengiriman', models.CharField(choices=[('dikirim', 'Dikirim'), ('dalam_perjalanan', 'Dalam Perjalanan'), ('diterima', 'Diterima')], max_length=50)),
                ('pengadaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barang.pengadaan')),
            ],
        ),
        migrations.AddField(
            model_name='pengadaan',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barang.supplier'),
        ),
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=255)),
                ('kategori', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok_tersedia', models.PositiveIntegerField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barang.supplier')),
            ],
        ),
    ]
